### ISSUE TITLE
[Wedding Tweaks] Cannot answer no to witness question

### ISSUE THREAD

**Issue by MegaPiggy** [aedenthorn/StardewValleyMods#17]
I walked up to Marnie and was asked if I wanted her to be a witness at my wedding and it wouldn't let me choose no. 
This error appears when I try to choose no.
```
An error occurred in the base update loop: System.Collections.Generic.KeyNotFoundException: The given key 'No' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71
   at WeddingTweaks.ModEntry.GameLocation_answerDialogueAction_Patch.Prefix(GameLocation __instance, String& questionAndAnswer, Boolean& __result) in C:\Users\poiqwe\source\repos\StardewValleyMods\WeddingTweaks\NPCPatches.cs:line 31
   at StardewValley.GameLocation.answerDialogueAction_PatchedBy<aedenthorn.FreeLove__aedenthorn.PlannedParenthood__aedenthorn.WeddingTweaks>(GameLocation this, String questionAndAnswer, String[] questionParams)
   at StardewValley.GameLocation.answerDialogue_PatchedBy<aedenthorn.FreeLove__aedenthorn.MobilePhone>(GameLocation this, Response answer)
   at StardewValley.Menus.DialogueBox.receiveLeftClick(Int32 x, Int32 y, Boolean playSound)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1._update(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 1055
```

**Comment by aedenthorn** [comment]
thanks, should be fixed in new version

**Comment by MegaPiggy** [comment]
It isn't fixed. It still happens.
